#!/bin/sh

export AWS_DEFAULT_PROFILE=tufts
aws ec2 describe-instances \
  --filters Name=tag:Name,Values=drio-nix-box Name=instance-state-name,Values=running \
  --query "Reservations[*].Instances[*].[InstanceId,PublicIpAddress,InstanceType]  " \
  --output=table

