#!/bin/sh

for s in `find . -maxdepth 1 -type d`
do
  [ "$s" = "." ] && continue
  name=$(echo $s | sed 's/\.\///')
  echo "$name"
  tmux attach-session -t $name || tmux new-session -s $name -d
  tmux send-keys -t $name "cd; cd dotfiles/nix/services/$name; ./start" C-m
done
