#!/bin/bash

profile=drio-tufts-solo
if [ ".$1" != "." ];then
  profile=$1
fi

(
cat <<EOF
export AWS_ACCESS_KEY_ID=$(aws configure get $profile.aws_access_key_id)
export AWS_SECRET_ACCESS_KEY=$(aws configure get $profile.aws_secret_access_key)
EOF
) | pbcopy
echo "✨"
