#!/bin/bash
# vim: ft=sh:
#
dir=$( dirname -- "$0"; )
source $dir/_scripts-env

ssh $backup_piip 'sudo mount -o defaults /dev/sda1 /mnt/external_drive_restic'
cd ~/dev/github.com/drio/restic-backup
make
cd -
