#!/bin/bash
# vim: ft=sh:
#
dir=$( dirname -- "$0"; )
source $dir/_scripts-env

echo "backup up hass"
b_dir=/Users/drio/dev/iot/hass-backups/backups
ssh gopher 'find /home/drio/dc/hass-config/backups -name "*.tar"  -mtime +7 -exec rm -f {} +;'
rsync --delete -avz -e ssh gopher:/home/drio/dc/hass-config/backups $b_dir/
n_backups=`find $b_dir -name "*.tar" | wc -l`
echo "# backup tar files: $n_backups"

#ssh $backup_piip 'sudo mount -o defaults /dev/sda1 /mnt/external_drive_restic'
cd ~/dev/github.com/drio/restic-backup
make
cd -
