#!/bin/bash
# vim: ft=sh:
set -e

start=$(date)
ts=/Applications/Tailscale.app/Contents/MacOS/Tailscale

function checkDir() {
	local dir=$1
	if [ ! -d "$dir" ]; then
		echo "directory $dir not there. Bailing out"
		exit 0
	fi
	echo "directory $dir found. good."
}

echo "Sudo just in case..."
sudo ls &>/dev/null

echo "switching tailnet"
currTailnet=$($ts switch --list | grep "*" | awk '{print $1}')
if [ currTailnet != "driodeiros@gmail.com" ]; then
	$ts switch driodeiros@gmail.com
fi

checkDir "/Volumes/drio-volume/restic-repo"

echo "syncing grafana backups"
grafDir="/Volumes/drio-volume/backups/grafana"
checkDir $grafDir
rsync -az -e ssh teton:grafana-dashboards-backups/ $grafDir

echo "syncing prometheus backups"
promDir="/Volumes/drio-volume/backups/prometheus"
checkDir $promDir
rsync -az -e ssh --progress teton:prometheus-snapshots/ $promDir

echo "Cleaning up reolink dirs in ds720..."
ssh ds720 'find /volume1/ftp-reolink -empty -type d -delete'
ssh ds720 'find /volume1/ftp-reolink -mindepth 3 -mtime 30 -exec rm -rv {} +;'

#echo "Nvim update ..."
#echo ""
#nvim-update

echo "homebrew ..."
echo ""
bubu

echo "homebrew (clean cache)..."
brew cleanup --prune=all

echo "Backup ..."
echo ""
backup

echo
echo "$start"
date
