#!/bin/bash
# vim: ft=sh:
set -e

socket=/tmp/nvim.sock
if [ ! -S $socket ];then
  echo "Socket not found: $socket"
  exit 0
fi

tab_name=$1
if [ ".$tab_name" == "." ];then
  echo "Usage: `basename $0` <tab_name>"
  exit 0
fi

nvim --server $socket --remote-send ":TabooOpen $tab_name<CR>"
nvim --server $socket --remote-send ":tcd `pwd`<CR>"
nvim --server $socket --remote .
