#!/bin/bash
# vim: ft=sh:
set -e

echo "Client cmd should be: /usr/local/bin/synergyc --no-daemon 192.168.8.38"
/opt/homebrew/opt/synergy-core/bin/synergys --config ~drio/.config/synergy.conf --no-daemon --name 192.168.8.55  --debug ERROR
