#!/bin/bash
# switch ts accounts
set -e

ts=tailscale
if [ $(uname -s) == "Darwin" ];then
  ts="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
fi

to=$1
if [ ".$to" == "." ];then
  switchTo=$($ts switch --list  | grep -v "*" | grep -v passkey | grep -v driode01)
else
  switchTo=$to
fi

$ts switch $switchTo
echo $switchTo
