#!/bin/bash
# vim: ft=sh:
set -e

FILE_RAW=$1
SPEED_FACTOR=${2:-1.0} # Default is 1.0 X speed

if [ ".$FILE_RAW" == "." ];then 
  echo "No input file provided" 
  echo "Usage $(basename $0) <input_file> [speed (default 1.0)]"
  exit 0
fi

# Prepare variables
BASE_PATH=$(dirname $(readlink -f $FILE_RAW))
FILENAME_EXT="$(basename "${FILE_RAW}")"
FILENAME_ONLY="${FILENAME_EXT%.*}"
EXT_ONLY="${FILENAME_EXT#*.}"
FILENAME_ONLY_PATH="${BASE_PATH}/${FILENAME_ONLY}"

# Speed up/slow down video
ffmpeg -i "${FILENAME_ONLY_PATH}.${EXT_ONLY}" \
  -vf "setpts=(PTS-STARTPTS)/${SPEED_FACTOR}" \
  -af atempo=$SPEED_FACTOR "${FILENAME_ONLY_PATH}_${SPEED_FACTOR}X.${EXT_ONLY}"
