#!/bin/bash
# vim: ft=sh:
set -e

date=$(date)
which gdate &> /dev/null
if [ $? -eq 0 ];then
  date=gdate
fi

# [18-24 July 2002]
y=$($date +"%Y")
m=$($date +"%B")
d1=$($date +"%d")
d2=$($date -d "+7 days" +"%d")

printf "[%s-%s] %s %s\n" $d1 $d2 $m $y
printf "[%s-%s] %s %s\n" $d1 $d2 $m $y | pbcopy
